name: "Test Suite"
on:
  push:
  pull_request:

jobs:
  test:
    name: cargo test
    environment: development
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly

      - run: cargo test
